site_name: Machine Learning
site_url: https://bobchrismansyah.github.io/Docs-Machine-Learning/

# Navigation
nav:
    - Home: index.md
    - About: about.md
    - Docs:
        - Docs: index.md
        - Pandas: docs/pandas/index.md
        - Neural Network: docs/neural-network/index.md
        - Naive Bayes: docs/naive-bayes/index.md
        - Logistic Regression: docs/logistic-regression/index.md
        - Decision Tree: docs/decision-tree/index.md
        - Clustering: docs/clustering/index.md
        - Churn Prediction: docs/churn-prediction/index.md
        
# Repository
repo_name: Docs-Machine-Learning
repo_url: https://github.com/BobChrismansyah/Docs-Machine-Learning
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2022 BobChrismansyah

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "theme"]
  icon:
    repo: fontawesome/brands/github
  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: id
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Ubuntu
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/bookshelf

# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:

  - minify:
      minify_html: true

# Customization
extra:
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BobChrismansyah

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - mdx_math
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: maling-it
      repo: maling-it.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML